-- ═══════════════════════════════════════════════════════════════════════════
-- Instance layer — clients, jobs, inspections, findings, evidence.
--
-- Derives from docs/GRAPH.md. Every column that exists because a regulation
-- demands it names its clause. Constraints encode the rules a spreadsheet
-- cannot enforce; that enforcement is most of the value of this system.
--
-- Requires 001 (template layer, generated by packages/checksheets).
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

-- ── enums ──────────────────────────────────────────────────────────────────

-- The 8 stages of the Assure Safety certification process flow.
CREATE TYPE job_stage AS ENUM (
  'enquiry',                 -- 1  triage: in scope?
  'application',             -- 2  application pack, quote, acceptance
  'document_review',         -- 3  desktop assessment
  'rfi',                     --    request for further information (loop back to 3)
  'site_inspection',         -- 4
  'compliance_evaluation',   -- 5
  'gap_closure',             --    client remediates (loop back to 5)
  'final_validation',        -- 6
  'certificate_issued',      -- 7
  'monitoring',              -- 8  ongoing support and renewal
  'closed',
  'referred'                 --    out of scope, referred elsewhere
);

CREATE TYPE finding_status AS ENUM (
  'pending',
  'compliant',
  'non_compliant',
  'not_applicable',
  'conditional'
);

CREATE TYPE certificate_decision AS ENUM ('granted', 'conditional', 'refused');

CREATE TYPE evidence_kind AS ENUM ('photo', 'video', 'document', 'branding');

-- How much we can actually vouch for a piece of evidence. Not cosmetic:
-- IPS 21(4) is an attestation, and 'migrated' means we cannot yet make it.
CREATE TYPE evidence_provenance AS ENUM (
  'c2pa',      -- signed C2PA manifest, hashed at the shutter
  'app',       -- captured in-app: hash + device + identity, no C2PA signature
  'migrated',  -- lifted from a legacy workbook; provenance unknown
  'none'
);

-- ── people ─────────────────────────────────────────────────────────────────

CREATE TABLE app_user (
  id                    bigserial PRIMARY KEY,
  full_name             text NOT NULL,
  -- IPS 21(4)(a) requires the OCCUPATION of whoever took a photograph, so it
  -- is a property of the person, captured once.
  occupation            text NOT NULL,
  email                 text,
  role                  text NOT NULL DEFAULT 'certifier'
                          CHECK (role IN ('certifier', 'assistant', 'admin')),
  -- IPS 8(1)(a),(b) — as printed on the WorkSafe document of authorisation.
  authorisation_number  text,
  signature_object_key  text,
  active                boolean NOT NULL DEFAULT true,
  created_at            timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN app_user.occupation IS
  'IPS cl. 21(4)(a): the occupation of the person who took a photograph must be recorded.';

-- Case-insensitive uniqueness without depending on the citext extension:
-- one fewer thing that must exist on whichever Postgres this is deployed to.
CREATE UNIQUE INDEX idx_app_user_email_lower ON app_user (lower(email))
  WHERE email IS NOT NULL;

-- ── client / site / location ───────────────────────────────────────────────

CREATE TABLE client (
  id               bigserial PRIMARY KEY,
  legal_name       text NOT NULL,
  trading_name     text,
  nzbn             text,
  companies_number text,           -- reg 6.26(2)(e)(ii)
  postal_address   text,
  phone            text,
  website          text,
  industry         text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE contact (
  id              bigserial PRIMARY KEY,
  client_id       bigint NOT NULL REFERENCES client(id) ON DELETE CASCADE,
  name            text NOT NULL,
  role            text,
  phone           text,
  email           text,
  is_site_manager boolean NOT NULL DEFAULT false
);

CREATE TABLE site (
  id        bigserial PRIMARY KEY,
  client_id bigint NOT NULL REFERENCES client(id) ON DELETE CASCADE,
  address   text NOT NULL
);

-- The unit of certification. IPS 21(1)(a): "the unique identification or
-- description of any item or location inquired into".
CREATE TABLE hs_location (
  id      bigserial PRIMARY KEY,
  site_id bigint NOT NULL REFERENCES site(id) ON DELETE CASCADE,
  name    text NOT NULL,           -- e.g. 'G2 Chiller'
  summary text,
  UNIQUE (site_id, name)
);

CREATE TABLE substance (
  id             bigserial PRIMARY KEY,
  hs_location_id bigint NOT NULL REFERENCES hs_location(id) ON DELETE CASCADE,
  name           text NOT NULL,
  un_number      text,
  hsno_approval  text,
  hazard_class   text NOT NULL,
  quantity       numeric,
  unit           text,
  sds_expiry     date
);

-- ── job: one certification engagement, walking the 8-stage flow ────────────

CREATE TABLE job (
  id             bigserial PRIMARY KEY,
  client_id      bigint NOT NULL REFERENCES client(id),
  hs_location_id bigint REFERENCES hs_location(id),
  stage          job_stage NOT NULL DEFAULT 'enquiry',
  class_key      text,             -- 'class_6_8' | 'class_2_3' — drives the overlay
  opened_at      timestamptz NOT NULL DEFAULT now(),
  closed_at      timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_job_stage ON job(stage) WHERE stage <> 'closed';
CREATE INDEX idx_job_client ON job(client_id);

-- Every stage change is a row, never an in-place edit. "When did this job
-- reach site inspection, and who moved it?" must be answerable at year nine.
CREATE TABLE job_stage_transition (
  id           bigserial PRIMARY KEY,
  job_id       bigint NOT NULL REFERENCES job(id) ON DELETE CASCADE,
  from_stage   job_stage,
  to_stage     job_stage NOT NULL,
  actor_id     bigint REFERENCES app_user(id),
  reason       text,
  occurred_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_transition_job ON job_stage_transition(job_id, occurred_at);

-- IPS 21(2)(a) — "every communication with the applicant about a matter
-- relevant to the application". A statutory record, same retention as the rest.
CREATE TABLE communication (
  id          bigserial PRIMARY KEY,
  job_id      bigint NOT NULL REFERENCES job(id) ON DELETE CASCADE,
  direction   text NOT NULL CHECK (direction IN ('inbound', 'outbound')),
  medium      text NOT NULL CHECK (medium IN ('email', 'phone', 'meeting', 'letter', 'other')),
  party       text NOT NULL,
  summary     text NOT NULL,
  body        text,
  occurred_at timestamptz NOT NULL,
  recorded_by bigint REFERENCES app_user(id),
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_communication_job ON communication(job_id, occurred_at);

-- IPS 23(1)-(3) — a register of interests is mandatory, and a certificate
-- must not issue without the conflict question having been asked.
CREATE TABLE interest_declaration (
  id             bigserial PRIMARY KEY,
  job_id         bigint NOT NULL REFERENCES job(id) ON DELETE CASCADE,
  certifier_id   bigint NOT NULL REFERENCES app_user(id),
  conflict_found boolean NOT NULL,
  description    text,
  mitigation     text,
  declared_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (job_id, certifier_id),
  -- A declared conflict without a description is not a declaration.
  CONSTRAINT conflict_needs_description
    CHECK (NOT conflict_found OR (description IS NOT NULL AND length(trim(description)) > 0))
);

-- ── inspection ─────────────────────────────────────────────────────────────

CREATE TABLE inspection (
  id             bigserial PRIMARY KEY,
  job_id         bigint NOT NULL REFERENCES job(id) ON DELETE CASCADE,
  hs_location_id bigint NOT NULL REFERENCES hs_location(id),

  certifier_id   bigint NOT NULL REFERENCES app_user(id),
  -- IPS 21(1)(g): where someone inspects on behalf of the certifier, their
  -- name AND whether they were supervised must both be recorded.
  conducted_by_id bigint REFERENCES app_user(id),
  supervised     boolean,

  inspected_at   timestamptz NOT NULL,             -- IPS 21(1)(b)
  equipment_used text NOT NULL,                    -- IPS 21(1)(d)

  status         text NOT NULL DEFAULT 'in_progress'
                   CHECK (status IN ('in_progress', 'complete')),
  created_at     timestamptz NOT NULL DEFAULT now(),

  -- If a different person conducted it, the supervision question must be
  -- answered. Leaving it null is the failure mode 21(1)(g) exists to prevent.
  CONSTRAINT supervision_recorded
    CHECK (conducted_by_id IS NULL OR conducted_by_id = certifier_id OR supervised IS NOT NULL),
  CONSTRAINT equipment_not_blank
    CHECK (length(trim(equipment_used)) > 0)
);

-- Which template revisions this inspection was conducted against. Pinning the
-- revision is what lets an auditor ask "which version of the standard?" in 2034
-- and get a real answer.
CREATE TABLE inspection_template (
  inspection_id bigint NOT NULL REFERENCES inspection(id) ON DELETE CASCADE,
  template_id   bigint NOT NULL REFERENCES checksheet_template(id),
  PRIMARY KEY (inspection_id, template_id)
);

-- ── finding: the result against one item. Replaces the workbook's font colour.
CREATE TABLE finding (
  id                  bigserial PRIMARY KEY,
  inspection_id       bigint NOT NULL REFERENCES inspection(id) ON DELETE CASCADE,
  item_id             bigint NOT NULL REFERENCES checksheet_item(id),

  status              finding_status NOT NULL DEFAULT 'pending',  -- IPS 21(1)(c)
  comment             text,
  verification_method text,                                        -- IPS 21(1)(e)
  failure_reason      text,                                        -- IPS 21(1)(f)

  decided_by          bigint REFERENCES app_user(id),
  decided_at          timestamptz,
  -- IPS 21(5): a record other than a photograph must be signed and dated by
  -- the certifier AND the person who did the inspection.
  certifier_signed_at timestamptz,
  inspector_signed_at timestamptz,

  updated_at          timestamptz NOT NULL DEFAULT now(),

  UNIQUE (inspection_id, item_id),

  -- IPS 21(1)(f): a non-compliance must state why. Enforced, not hoped for.
  CONSTRAINT non_compliance_needs_reason
    CHECK (status <> 'non_compliant'
           OR (failure_reason IS NOT NULL AND length(trim(failure_reason)) > 0))
);

CREATE INDEX idx_finding_inspection ON finding(inspection_id);
CREATE INDEX idx_finding_status ON finding(status) WHERE status = 'non_compliant';

CREATE TABLE corrective_action (
  id             bigserial PRIMARY KEY,
  finding_id     bigint NOT NULL REFERENCES finding(id) ON DELETE CASCADE,
  severity       text NOT NULL CHECK (severity IN ('critical', 'major', 'minor')),
  description    text NOT NULL,
  due_date       date,
  status         text NOT NULL DEFAULT 'open'
                   CHECK (status IN ('open', 'in_progress', 'resolved', 'verified')),
  reverified_by  bigint REFERENCES app_user(id),
  reverified_at  timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now(),

  -- 'verified' is a claim about a person having re-checked it. Require both.
  CONSTRAINT verified_needs_verifier
    CHECK (status <> 'verified' OR (reverified_by IS NOT NULL AND reverified_at IS NOT NULL))
);

-- ── evidence ───────────────────────────────────────────────────────────────

CREATE TABLE evidence (
  id                     bigserial PRIMARY KEY,
  job_id                 bigint NOT NULL REFERENCES job(id) ON DELETE CASCADE,
  inspection_id          bigint REFERENCES inspection(id) ON DELETE SET NULL,
  finding_id             bigint REFERENCES finding(id) ON DELETE SET NULL,

  kind                   evidence_kind NOT NULL,
  -- Content-addressed: the object key IS the hash. The same photo filed twice
  -- is one object; a renamed file is still the same record.
  sha256                 char(64) NOT NULL,
  storage_key            text NOT NULL,
  mime                   text NOT NULL,
  bytes                  bigint NOT NULL CHECK (bytes > 0),

  -- IPS 21(4) — mandatory for any photograph used as a record.
  captured_by_name       text,
  captured_by_occupation text,
  captured_at            timestamptz,
  captured_where         text,

  -- Supporting, never a substitute for captured_where: 21(4)(c) asks where the
  -- photograph was taken, which is a place a human can read, not a coordinate.
  gps_lat                double precision,
  gps_lon                double precision,
  device_info            text,

  provenance             evidence_provenance NOT NULL DEFAULT 'none',
  c2pa_manifest          bytea,

  appendix_category      text,     -- the 11-appendix filing taxonomy
  retain_until           date,     -- IPS 21(6), drives object-lock retention

  created_at             timestamptz NOT NULL DEFAULT now(),

  -- A photo or video captured through the app must carry its 21(4) provenance.
  -- 'migrated' is the deliberate escape hatch for legacy workbook images, and
  -- it is visible in the data rather than hidden behind nulls.
  CONSTRAINT ips_21_4_provenance CHECK (
    kind NOT IN ('photo', 'video')
    OR provenance IN ('migrated', 'none')
    OR (captured_by_name IS NOT NULL
        AND captured_by_occupation IS NOT NULL
        AND captured_at IS NOT NULL
        AND captured_where IS NOT NULL)
  ),
  CONSTRAINT c2pa_needs_manifest
    CHECK (provenance <> 'c2pa' OR c2pa_manifest IS NOT NULL)
);

CREATE INDEX idx_evidence_job ON evidence(job_id);
CREATE INDEX idx_evidence_finding ON evidence(finding_id);
CREATE INDEX idx_evidence_sha ON evidence(sha256);
-- Evidence still inside its statutory retention window.
CREATE INDEX idx_evidence_retention ON evidence(retain_until) WHERE retain_until IS NOT NULL;

COMMENT ON CONSTRAINT ips_21_4_provenance ON evidence IS
  'IPS cl. 21(4): a photograph used as a record must carry the name and occupation of the photographer, the date, and the place. provenance = migrated marks legacy images that cannot yet satisfy this.';

-- ── certificate ────────────────────────────────────────────────────────────

CREATE TABLE certificate (
  id                    bigserial PRIMARY KEY,
  job_id                bigint NOT NULL UNIQUE REFERENCES job(id),
  inspection_id         bigint REFERENCES inspection(id),

  decision              certificate_decision NOT NULL,

  -- IPS 8(1)(c): EITHER the unique register number, OR a certifier-assigned
  -- number prefixed with the authorisation number, or both.
  register_number       text,
  certificate_number    text,

  certifier_id          bigint NOT NULL REFERENCES app_user(id),  -- 8(1)(a),(b)
  issued_to             text NOT NULL,                            -- 8(1)(f)
  applies_to            text NOT NULL,                            -- 8(1)(g)

  issue_date            date NOT NULL,                            -- 8(1)(e)
  in_force_date         date NOT NULL,                            -- 8(1)(h)
  expiry_date           date,                                     -- 8(1)(i)

  details               text,
  requirements_not_met  text[] NOT NULL DEFAULT '{}',
  conditions            text[] NOT NULL DEFAULT '{}',             -- reg 6.24

  signed_at             timestamptz,                              -- 8(2)(a); 8(3) e-sig ok
  -- reg 6.22(5): 15 working days to enter the certificate in the register.
  worksafe_register_due date,
  worksafe_registered_at timestamptz,

  created_at            timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT has_a_number
    CHECK (register_number IS NOT NULL OR certificate_number IS NOT NULL),
  -- reg 6.24: a conditional certificate without conditions is incoherent.
  -- cardinality(), not array_length(): array_length('{}',1) is NULL, and a
  -- CHECK only fails on FALSE, so the array_length form is silently inert.
  CONSTRAINT conditional_needs_conditions
    CHECK (decision <> 'conditional' OR cardinality(conditions) > 0),
  -- reg 6.23(2): a refusal must say what was not met.
  CONSTRAINT refusal_needs_reasons
    CHECK (decision <> 'refused' OR cardinality(requirements_not_met) > 0),
  CONSTRAINT dates_ordered
    CHECK (in_force_date >= issue_date
           AND (expiry_date IS NULL OR expiry_date > in_force_date))
);

-- IPS 21(6) — retain until 5 years after expiry (10 years after issue for
-- cylinder / tank-wagon types). One row per job, computed, never remembered.
CREATE TABLE retention_clock (
  id             bigserial PRIMARY KEY,
  job_id         bigint NOT NULL UNIQUE REFERENCES job(id) ON DELETE CASCADE,
  certificate_id bigint REFERENCES certificate(id),
  trigger        text NOT NULL CHECK (trigger IN ('expiry_plus_5y', 'issue_plus_10y', 'refusal_plus_5y')),
  retain_until   date NOT NULL,
  created_at     timestamptz NOT NULL DEFAULT now()
);

COMMIT;
